<?php

namespace ContainerX6uJk3f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_Orm_ContainerRepositoryFactoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'doctrine.orm.container_repository_factory' shared service.
     *
     * @return \Doctrine\Bundle\DoctrineBundle\Repository\ContainerRepositoryFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/Repository/RepositoryFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/RepositoryFactoryCompatibility.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ContainerRepositoryFactory.php';

        return $container->privates['doctrine.orm.container_repository_factory'] = new \Doctrine\Bundle\DoctrineBundle\Repository\ContainerRepositoryFactory(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Database\\Repository\\AuthStatisticsRepository' => ['privates', 'App\\Database\\Repository\\AuthStatisticsRepository', 'getAuthStatisticsRepositoryService', true],
            'App\\Database\\Repository\\CLoginRepository' => ['privates', 'App\\Database\\Repository\\CLoginRepository', 'getCLoginRepositoryService', true],
            'App\\Database\\Repository\\CNumRepository' => ['privates', 'App\\Database\\Repository\\CNumRepository', 'getCNumRepositoryService', true],
            'App\\Database\\Repository\\DtPropertiesRepository' => ['privates', 'App\\Database\\Repository\\DtPropertiesRepository', 'getDtPropertiesRepositoryService', true],
            'App\\Database\\Repository\\ExpTableRepository' => ['privates', 'App\\Database\\Repository\\ExpTableRepository', 'getExpTableRepositoryService', true],
            'App\\Database\\Repository\\GuildRankRepository' => ['privates', 'App\\Database\\Repository\\GuildRankRepository', 'getGuildRankRepositoryService', true],
            'App\\Database\\Repository\\IPRepository' => ['privates', 'App\\Database\\Repository\\IPRepository', 'getIPRepositoryService', true],
            'App\\Database\\Repository\\IpLogRepository' => ['privates', 'App\\Database\\Repository\\IpLogRepository', 'getIpLogRepositoryService', true],
            'App\\Database\\Repository\\ItemBuyBackupRepository' => ['privates', 'App\\Database\\Repository\\ItemBuyBackupRepository', 'getItemBuyBackupRepositoryService', true],
            'App\\Database\\Repository\\ItemBuyRepository' => ['privates', 'App\\Database\\Repository\\ItemBuyRepository', 'getItemBuyRepositoryService', true],
            'App\\Database\\Repository\\ItemDetailRepository' => ['privates', 'App\\Database\\Repository\\ItemDetailRepository', 'getItemDetailRepositoryService', true],
            'App\\Database\\Repository\\ItemInfoRepository' => ['privates', 'App\\Database\\Repository\\ItemInfoRepository', 'getItemInfoRepositoryService', true],
            'App\\Database\\Repository\\LogRepository' => ['privates', 'App\\Database\\Repository\\LogRepository', 'getLogRepositoryService', true],
            'App\\Database\\Repository\\LoginDeletedRepository' => ['privates', 'App\\Database\\Repository\\LoginDeletedRepository', 'getLoginDeletedRepositoryService', true],
            'App\\Database\\Repository\\LoginRepository' => ['privates', 'App\\Database\\Repository\\LoginRepository', 'getLoginRepositoryService', true],
            'App\\Database\\Repository\\PrizeWinnerRepository' => ['privates', 'App\\Database\\Repository\\PrizeWinnerRepository', 'getPrizeWinnerRepositoryService', true],
            'App\\Database\\Repository\\RankRepository' => ['privates', 'App\\Database\\Repository\\RankRepository', 'getRankRepositoryService', true],
            'App\\Database\\Repository\\UserIpRepository' => ['privates', 'App\\Database\\Repository\\UserIpRepository', 'getUserIpRepositoryService', true],
        ], [
            'App\\Database\\Repository\\AuthStatisticsRepository' => '?',
            'App\\Database\\Repository\\CLoginRepository' => '?',
            'App\\Database\\Repository\\CNumRepository' => '?',
            'App\\Database\\Repository\\DtPropertiesRepository' => '?',
            'App\\Database\\Repository\\ExpTableRepository' => '?',
            'App\\Database\\Repository\\GuildRankRepository' => '?',
            'App\\Database\\Repository\\IPRepository' => '?',
            'App\\Database\\Repository\\IpLogRepository' => '?',
            'App\\Database\\Repository\\ItemBuyBackupRepository' => '?',
            'App\\Database\\Repository\\ItemBuyRepository' => '?',
            'App\\Database\\Repository\\ItemDetailRepository' => '?',
            'App\\Database\\Repository\\ItemInfoRepository' => '?',
            'App\\Database\\Repository\\LogRepository' => '?',
            'App\\Database\\Repository\\LoginDeletedRepository' => '?',
            'App\\Database\\Repository\\LoginRepository' => '?',
            'App\\Database\\Repository\\PrizeWinnerRepository' => '?',
            'App\\Database\\Repository\\RankRepository' => '?',
            'App\\Database\\Repository\\UserIpRepository' => '?',
        ]));
    }
}
