<?php

namespace ContainerX6uJk3f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDemoContextService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Tests\Behat\DemoContext' shared autowired service.
     *
     * @return \App\Tests\Behat\DemoContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
        include_once \dirname(__DIR__, 4).'/tests/Behat/DemoContext.php';

        return $container->services['App\\Tests\\Behat\\DemoContext'] = new \App\Tests\Behat\DemoContext(($container->services['kernel'] ?? $container->get('kernel', 1)));
    }
}
