<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMa5jBwS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMa5jBwS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMa5jBwS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMa5jBwS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMa5jBwS\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ma5jBwS',
    'container.build_id' => '508ce8c0',
    'container.build_time' => 1723044407,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMa5jBwS');
